### ISSUE TITLE
HTTP header in subject and body

### ISSUE THREAD

**Issue by minthemiddle** [bolt/boltforms#142] opened 2017-03-16 11:11 UTC
In my example form that I use on a localhost with latest Bolt and BoltForms I'm using `mailhog` to test my email settings.

When I set up the example `contact` form on my site, I get header information in both header and body.

`Debug` is disabled.

![bildschirmfoto 2017-03-16 um 12 07 42](https://cloud.githubusercontent.com/assets/1950766/23993552/4ab34100-0a41-11e7-920c-df576ac622ff.png)

**Comment by rossriley** [comment] 2017-04-15 11:17
@minthemiddle Thanks for logging the issue, I'm just trying to reproduce this, can you let me know what version numbers you've tested this against, as I think it seems to be working ok in the latest beta version. If you were working on the stable 3.x latest version then we can look at getting it back ported.

Screenshot of result in Mailhog using Bolt 3.3-beta-5 and BoltForms 4.0-beta-2 below.

![screen shot 2017-04-15 at 12 13 20](https://cloud.githubusercontent.com/assets/5082/25063159/faf949ec-21d4-11e7-8a28-e8651199753d.png)

**Comment by jamieburchell** [comment] 2017-07-28 09:53
Run in to exactly this on Bolt Forms 3.1.0 and Bolt 3.3.0. Email subject is appended with:

HTTP/1.0 200 OK Cache-Control: no-cache Date: Fri, 28 Jul 2017 09:40:35 GMT

**Comment by jamieburchell** [comment] 2017-07-28 10:08
Rolling back to Bolt v3.2.13 has resolved this for me (I rolled back a composer update).

**Comment by bobdenotter** [comment] 2017-12-29 15:17
This is fixed, if you're using the latest Bolt & BoltForms. 

Closing, unless somebody is still bumping into it on the latest versions.

**Closed by bobdenotter** 2017-12-29 15:17 UTC

**Comment by eduardomart** [comment] 2018-07-28 04:36
I am seeing this on Bolt 3.5.5 with BoltForms 3.1.0

**Comment by SahAssar** [comment] 2018-07-29 15:52
@eduardomart the latest boltforms is v4.2.3. Please upgrade to that and see if the issue persists.

**Comment by eduardomart** [comment] 2018-07-29 21:05
@SahAssar I did, but I find it strange that BF never told me there was an update when I was using 3.x

**Comment by SahAssar** [comment] 2018-07-29 21:45
@eduardomart The updater only suggests you update to minor and patch versions. just like semver says. If you want to update the major version you will need to explicitly do so as it can include breaking changes.

**Comment by jadwigo** [comment] 2018-07-31 08:38
@eduardomart The update from boltforms 3.x to 4.x has some changes in the templates. If you have any customized templates for the forms in your site those changes might be breaking your site, so you might need to rebuild any custom form templates then
